### ISSUE TITLE
consider gcp for the next tutorial

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/ansible-playbook-workhorse#1]
https://edu.google.com/programs/credits/?modal_active=none

**Comment by chrisjsewell** [comment]
@ltalirz shall I close this? Was there any reason you had in mind why to choose GCP over AWS?

**Comment by ltalirz** [comment]
this was just a "note to self" as you can apply for free credits there as faculty
anyhow, AWS is not too expensive for us either
